In [1]:
import numpy as np


In [7]:
arr = np.zeros(64).reshape(8, 8)

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [8]:
varinace = 5

stddev = np.sqrt(varinace)

random_arr = np.random.normal(scale = stddev, size = 20000)

print(random_arr.mean())
print(random_arr.var())


0.032016795696047116
5.018461959223587
